import Head from 'next/head'
import Image from 'next/image'
import Card from '@components/components/Card'
import styles from '../styles/Characters.module.css'
import YoutubeEmbed from '@components/components/YoutubeEmbed'
import Pagination from '@components/components/Pagination'
import { useState } from 'react'
import { paginate } from '@components/helpers/paginate'

export const getStaticProps = async () => {
  const res= await fetch('http://gateway.marvel.com/v1/public/characters?ts=1&apikey=5c0ac94ae46c3f7242300871fa61952c&hash=6bc9123d784f5c98b1a2790c76e0e013')
  const data = await res.json()

  return {
    props: { characters: data.data.results}
  }
}

const Characters = ({characters}) =>{
  console.log(characters.length);

  const charactersPerPage= 5;

  const [currentPage, setCurrentPage]=useState(1)

  const onPageChange = (page) =>{
    setCurrentPage(page)
  }

  const paginatedCharacters= paginate(characters, currentPage, charactersPerPage)

  return(
    <>
    <Head>
        <title>Marvel | Personajes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marvel.png" />
      </Head>
      <main>
        <div className={styles.infoContainer}>
          <div className={styles.progress}>PROGRESO DE PELICULAS PRODUCIDAS</div>
          <div>
            <YoutubeEmbed embedId='VgBKUofIdVo'/>
          </div>
          <div>
            <Image
              src="https://wallpapershome.com/images/pages/pic_h/17945.jpg"
              alt="avengers poster"
              width={0}
              height={0}
              sizes="100vw"
              style={{ width: '100%', height: 'auto' }}
            />
          </div>
        </div>
        <div className={styles.cardsContainer}>

          {paginatedCharacters.map((character)=>(
            <Card key={character.name} name={character.name} image={character.thumbnail.path.concat('.',character.thumbnail.extension)} comics={character.comics.available} movies={character.series.available} />
          ))}

        </div>

        <Pagination items={characters.length} currentPage={currentPage} pageSize={charactersPerPage} onPageChange={onPageChange}/>

      </main>

    </>
    
  )
}

export default Characters