import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@components/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Marvel | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/marvel.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>MARVEL UNIVERSE</h1>
        <p className={styles.text}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad neque
          voluptate beatae ducimus fugiat iste repellendus illum maiores aperiam
          molestiae distinctio similique, eum, culpa dolores explicabo suscipit
          obcaecati nisi consequuntur.
        </p>
        <p className={styles.text}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad neque
          voluptate beatae ducimus fugiat iste repellendus illum maiores aperiam
          molestiae distinctio similique, eum, culpa dolores explicabo suscipit
          obcaecati nisi consequuntur.
        </p>
      </main>
    </>
  )
}
